alias recette='figlet "60% rhum, 40% fruits frais et un peu de l ingredient secret"'
alias lock='./lock.py'
alias chat='./chat.py'
alias whash_your_hands='figlet "... done"'
alias put_the_mask_on='figlet "... done"'
alias put_the_mask_off='figlet "... done"'
alias WEI_ON='export WEI=1 && figlet "WEI is on"'
alias WEI_OFF='export WEI=0 && figlet "WEI is off"'
alias loading='node usb.js'
alias WII='figlet Thomassss Delmas vs Guetguet Falcanihio'
alias micro-onde='figlet Beeeeeeeatriz'
alias bitcoin='echo "Tié fou toi ou quoi"'
alias cheville='figlet "Reparation impossible, les dommages sont trop importants..."'
alias horloge='figlet "Ca fait crack"'
alias solve_all_sudoku='echo "sois patient tu vas bientot comprendre cette vanne"'
alias pml='./pml.sh'
alias hack_if='./hack_if.py'